<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class ProdutoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Opcional: Para garantir que a seeder possa ser executada várias vezes sem criar dados duplicados,
        // é uma boa prática limpar a tabela antes de inserir os novos dados.
        // Descomente as linhas abaixo se desejar este comportamento.

        // Schema::disableForeignKeyConstraints();
        // DB::table('produtos')->truncate();
        // Schema::enableForeignKeyConstraints();

        DB::table('produtos')->insert([
            [
                'id' => 10,
                'categoria_id' => 4,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67eaf2fd2b1c2-collect-31-03-25-.svg',
                'titulo' => 'CHAISE EUROPA  TRAMA X',
                'descricao' => "VALOR CONJUNTO ILUSTRADO\r\n\r\nDIAMETRO 0,90:\r\n R\$2.787,00\r\n\r\n DIAMETRO 1,20:\r\n R\$3.608,00\r\n\r\n DIAMETRO 1,70:\r\n R\$5.550,00\r\n  \r\nESPECIFICAÇÕES:\r\n ESTRUTURA EM ALUMINIO\r\n PINTURA ELETROSTATICA\r\n CORDA NAUTICA\r\n TECIDO ACQUABLOCK",
                'valor' => '2787',
                'valor_promocional' => 2500.00,
                'slug' => 'chaise-europa-trama-x',
                'status' => 1,
                'created_at' => '2025-03-31 19:54:37',
                'updated_at' => '2025-10-08 16:58:42',
            ],
            [
                'id' => 11,
                'categoria_id' => 4,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67eaf33d1c05a-collect-31-03-25-.svg',
                'titulo' => 'CHAISE TRADICIONAL  TRAMA TELINHA',
                'descricao' => "DIAMETRO 1,20:\r\n R\$3.465,00\r\n\r\n DIAMETRO 1,30:\r\n R\$3.708,00\r\n\r\n DIAMETRO 1,40:\r\n R\$3.968,00\r\n\r\n DIAMETRO 1,50:\r\n R\$4.245,00\r\n\r\n DIAMETRO 1,60:\r\n R\$4.543,00\r\n\r\n DIAMETRO 1,70:\r\n R\$4.860,00",
                'valor' => '3465',
                'valor_promocional' => 3000.00,
                'slug' => 'chaise-tradicional-trama-telinha',
                'status' => 1,
                'created_at' => '2025-03-31 19:55:41',
                'updated_at' => '2025-10-08 16:58:54',
            ],
            [
                'id' => 12,
                'categoria_id' => 4,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67eaf3a0ea5a4-collect-31-03-25-.svg',
                'titulo' => 'CHAISE TRADICIONAL  TRAMA VAI E VEM',
                'descricao' => "DIAMETRO 1,20\r\n R\$2.787,00\r\n\r\n DIAMETRO 1,30:\r\n R\$3.064,00\r\n\r\n DIAMETRO 1,40:\r\n R\$3.330,00\r\n\r\n DIAMETRO 1,50\r\n R\$3.689,00\r\n\r\n DIAMETRO 1,60:\r\n R\$3.985,00\r\n\r\n DIAMETRO 1,70:\r\n R\$4.302,00",
                'valor' => '2787',
                'valor_promocional' => 2400.00,
                'slug' => 'chaise-tradicional-trama-vai-e-vem',
                'status' => 1,
                'created_at' => '2025-03-31 19:57:20',
                'updated_at' => '2025-10-08 16:59:04',
            ],
            [
                'id' => 13,
                'categoria_id' => 4,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67eaf3ca39fe8-collect-31-03-25-.svg',
                'titulo' => 'CHAISE BAULADA',
                'descricao' => "DIAMETRO 1,20:\r\n R\$3.300,00\r\n\r\n DIAMETRO 1,30:\r\n R\$3.530,00\r\n\r\n DIAMETRO 1,40:\r\n R\$3.779,00\r\n\r\n DIAMETRO 1,50:\r\n R\$4.043,00\r\n\r\n DIAMETRO 1,60:\r\n R\$4.320,00\r\n\r\n DIAMETRO 1,70:\r\n R\$4.629,00",
                'valor' => '3300',
                'valor_promocional' => null,
                'slug' => 'chaise-baulada',
                'status' => 1,
                'created_at' => '2025-03-31 19:58:02',
                'updated_at' => '2025-03-31 19:58:02',
            ],
            [
                'id' => 14,
                'categoria_id' => 5,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67eaf451c06e9-collect-31-03-25-.svg',
                'titulo' => 'CONJUNTO SOFÁ  BARCELONA',
                'descricao' => "2 - MÓDULOS LATERAIS 1,50M (SENDO 0,30M MESINHA + 1,20M SOFÁ)\r\n1 - MÓDULO DE 1,80M + MESA LATERAL DE 0,90M \r\n1 - MESA DE CENTRO 0,90M X 0,70M\r\n\r\n VALOR DO SOFÁ - 5,70M X R\$3.360,00\r\n R\$19.152,00\r\n\r\n MESA DE CENTRO:\r\n R\$2.825,00\r\n\r\n VALOR DO CONJUNTO:\r\n R\$21.977,00",
                'valor' => '21977',
                'valor_promocional' => 19599.00,
                'slug' => 'conjunto-sofa-barcelona',
                'status' => 1,
                'created_at' => '2025-03-31 20:00:17',
                'updated_at' => '2025-04-01 01:49:58',
            ],
            [
                'id' => 15,
                'categoria_id' => 5,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67eaf4a1c5e6e-collect-31-03-25-.svg',
                'titulo' => 'CONJUNTO DE SOFÁ  LOTUS',
                'descricao' => "DIMENSÕES:\r\n PROFUNDIDADE TOTAL - 0,80M\r\n ALTURA DO ACENTO - 0,40M\r\n LARGURA DOS MODULOS - 2,40M(SOFÁ) + 0,30M(MESA LATERAL) + 1,60M(SOFÁ) + 0,30M(MESA LATERAL)\r\n VALOR POR METRO\r\n R\$3.190,00\r\n\r\n VALOR DO CONJUNTO ILUSTRADO:\r\n R\$14.674,00",
                'valor' => '14674',
                'valor_promocional' => null,
                'slug' => 'conjunto-de-sofa-lotus',
                'status' => 1,
                'created_at' => '2025-03-31 20:01:37',
                'updated_at' => '2025-03-31 20:01:37',
            ],
            [
                'id' => 16,
                'categoria_id' => 5,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67eaf624c4740-collect-31-03-25-.svg',
                'titulo' => 'SOFÁ MARROCOS',
                'descricao' => "DIMENSÕES:\r\nSOFÁ MARROCOS - \r\nLARGURA TOTAL - 2,10M\r\nLARGURA DO ACENTO -0,64M\r\nPROFUNDIDADE TOTAL - 0,86M\r\nPROFUNDIDADE DO ACENTO - 0,65M\r\nALTURA DO ACENTO 0,45M\r\nR\$10.597,00\r\n\r\nPOLTRONA MARROCOS TRAMA FECHADA CORDA NAUTICA PÉ EM MADEIRA CUMARU -\r\nLARGURA TOTAL - 1,00M\r\nLARGURA DO ACENTO - 0,64M\r\nPROFUNDIDADE TOTAL - 0,86M\r\nPROFUNDIDADE DO ACENTO - 0,65M\r\nALTURA DO ACENTO - 0,45M\r\nR\$4.871,00\r\n\r\nMESA DE CENTRO MARROCOS TRAMA FECHADA CORDA NAUTICA TAMPO EM MADEIRA CUMARU -\r\nLARGURA TOTAL - 0,60M\r\nPROFUNDIDADE TOTAL - 0,50M\r\nALTURA TOTAL - 0,45M\r\nR\$2.467,00\r\n\r\n VALOR DO CONJUNTO:\r\n R\$22.806,00",
                'valor' => '22806',
                'valor_promocional' => null,
                'slug' => 'sofa-marrocos',
                'status' => 1,
                'created_at' => '2025-03-31 20:08:04',
                'updated_at' => '2025-03-31 20:08:04',
            ],
            [
                'id' => 17,
                'categoria_id' => 5,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67eaf716947ae-collect-31-03-25-.svg',
                'titulo' => 'NAMORADEIRA EXCLUSIVA',
                'descricao' => "DESCRISÕES:\r\n\r\nNAMORADEIRA EXCLUSIVA:\r\nLARGURA TOTAL - 1,40M\r\nLARGURA DO ACENTO - 1,35M\r\nALTURA TOTAL - 0,85M\r\nALTURA DO ACENTO - 0,38M\r\nPROFUNDIDADE TOTAL - 0,80M\r\nPROFUNDIDADE DO ACENTO -0,80M\r\nR\$4.665,00\r\n\r\nPOLTRONA EXCLUSIVA CORDA NAUTICA PÉ EM MADEIRA CUMARU \r\nLARGURA TOTAL - 0,80M\r\nLARGURA DO ACENTO - 0,75M\r\nALTURA TOTAL - 0,85M\r\nALTURA DO ACENTO - 0,38M\r\nPROFUNDIDADE TOTAL - 0,80M\r\nPROFUNDIDADE DO ACENTO - 0,80M\r\nR\$3.270,00\r\n\r\nPUFF PREMIUM M CORDA NAUTICA TAMPO EM MADEIRA CUMARU\r\nDIAMETRO TOTAL - 0,40M\r\nALTURA TOTAL - 0,52M\r\nR\$1.305,00\r\n\r\nVALOR DO CONJUNTO R\$12.510,00",
                'valor' => '12510',
                'valor_promocional' => null,
                'slug' => 'namoradeira-exclusiva',
                'status' => 1,
                'created_at' => '2025-03-31 20:12:06',
                'updated_at' => '2025-03-31 20:12:06',
            ],
            [
                'id' => 18,
                'categoria_id' => 5,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67eaf7be61ec9-collect-31-03-25-.svg',
                'titulo' => 'SOFÁ VINALES',
                'descricao' => "DESCRIÇÃO\r\n\r\nSOFÁ VINALES TRAMA FECHADA CN PÉ EM MADEIRA CUMARU\r\nLARGURA TOTAL - 2,10M\r\nPROFUNDIDADE TOTAL - 0,86M\r\nPROFUNDIDADE DO ACENTO - 0,65M\r\nALTURA DO ACENTO 0,45M\r\nR\$9.377,00\r\n\r\nPOLTRONA VINALES TRAMA FECHADA CORDA NAUTICA PÉ EM MADEIRA CUMARU\r\nLARGURA TOTAL - 1,00M\r\nPROFUNDIDADE TOTAL - 0,86M\r\nPROFUNDIDADE DO ACENTO - 0,65M\r\nALTURA DO ACENTO - 0,45M\r\nR\$4.670,00\r\n\r\nMESA DE CENTRO VINALES TRAMA FECHADA CORDA NAUTICA TAMPO EM VIDRO \r\nLARGURA TOTAL - 0,60M\r\nPROFUNDIDADE TOTAL - 0,60M\r\nALTURA TOTAL - 0,45M\r\nR\$2.261,00\r\n\r\nVALOR DO CONJUNTO R\$20.978,00",
                'valor' => '20978',
                'valor_promocional' => null,
                'slug' => 'sofa-vinales',
                'status' => 1,
                'created_at' => '2025-03-31 20:14:54',
                'updated_at' => '2025-03-31 20:14:54',
            ],
            [
                'id' => 19,
                'categoria_id' => 5,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67eaf85f60f27-collect-31-03-25-.svg',
                'titulo' => 'SOFÁ VIENA',
                'descricao' => "DESCRIÇÃO:\r\n\r\nSOFÁ VIENA CN PÉ EM MADEIRA CUMARU\r\nLARGURA TOTAL - 2,10M\r\nLARGURA DO ACENTO - 1,88M\r\nALTURA TOTAL - 0,68M\r\nPROFUNDIDADE TOTAL - 0,78M\r\nPROFUNDIDADE DO ACENTO - 0,65M\r\nR\$5.745,00\r\n\r\nPOLTRONA VIENA CORDA NAUTICA PÉ EM MADEIRA CUMARU\r\nLARGURA TOTAL - 0,78M\r\nLARGURA DO ACENTO - 0,53M\r\nALTURA TOTAL - 0,68M\r\nPROFUNDIDADE TOTAL - 0,78M\r\nPROFUNDIDADE DO ACENTO - 0,65M\r\nR\$3.216,00\r\n\r\nPUFF VIENA CORDA NAUTICA\r\nLARGURA TOTAL - 0,60M\r\nCOMPRIMENTO TOTAL - 0,75M\r\nALTURA TOTAL - 0,50M\r\nR\$1.080,00\r\n\r\nVALOR DO CONJUNTO R\$13.257,00",
                'valor' => '13257',
                'valor_promocional' => null,
                'slug' => 'sofa-viena',
                'status' => 1,
                'created_at' => '2025-03-31 20:17:35',
                'updated_at' => '2025-03-31 20:17:35',
            ],
            [
                'id' => 20,
                'categoria_id' => 5,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67eaf9b18bee6-collect-31-03-25-.svg',
                'titulo' => 'SOFÁ NAPOLES',
                'descricao' => "DESCRIÇÃO\r\n\r\nSOFÁ NAPOLES CORDA NAUTICA\r\nLARGURA TOTAL - 1,71M\r\nPROFUNDIDADE TOTAL - 0,71M\r\nPROFUNDIDADE DO ACENTO - 0,60M\r\nALTURA DO ACENTO 0,36M\r\nR\$3.936,00\r\n\r\nPOLTRONA NAPOLES CORDA NAUTICA\r\nLARGURA TOTAL - 0,73M\r\nPROFUNDIDADE TOTAL - 0,71M\r\nPROFUNDIDADE DO ACENTO - 0,60M\r\nALTURA DO ACENTO - 0,36M\r\nR\$2.605,00\r\n\r\nCHAMPANHEIRA TRAMA FECHADA CORDA NAUTICA 22MM\r\nDIAMETRO TOTAL - 0,70M\r\nALTURA TOTAL - 0,37M\r\nR\$3.260,00\r\n\r\nVALOR DO CONJUNTO R\$12.406,00",
                'valor' => '12406',
                'valor_promocional' => null,
                'slug' => 'sofa-napoles',
                'status' => 1,
                'created_at' => '2025-03-31 20:23:13',
                'updated_at' => '2025-03-31 20:23:13',
            ],
            [
                'id' => 21,
                'categoria_id' => 5,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67eafa743037c-collect-31-03-25-.svg',
                'titulo' => 'NAMORADEIRA TAJ - TRAMA VAI E VEM',
                'descricao' => "DESCRIÇÃO\r\n\r\nNAMORADEIRA TAJ TRAMA  VAI E VEM CN\r\nLARGURA TOTAL - 1,30M\r\nLARGURA DO ACENTO - 1,20M\r\nPROFUNDIDADE TOTAL - 0,65M\r\nPROFUNDIDADE DO ACENTO - 0,58M\r\nALTURA DO ACENTO 0,43M\r\nR\$2.705,00\r\n\r\nPOLTRONA TAJ TRAMA VAI E VEM CORDA NAUTICA\r\nLARGURA TOTAL - 0,65M\r\nLARGURA DO ACENTO - 0,55M\r\nPROFUNDIDADE TOTAL - 0,65M\r\nPROFUNDIDADE DO ACENTO - 0,58M\r\nALTURA DO ACENTO - 0,43M\r\nR\$1.719,00\r\n\r\nPUFF PREMIUM P TRAMA VAI E VEM CORDA NAUTICA TAMPO EM MADEIRA CUMARU\r\nDIAMETRO TOTAL - 0,40M\r\nALTURA TOTAL - 0,42M\r\nR\$1.115,00\r\n\r\nPUFF GARDEN MARECIAS CORDA NAUTICA TAMPO EM MADEIRA CUMARU\r\nDIAMETRO TOTAL - 0,40M\r\nALTURA TOTAL - 0,42M\r\nR\$1.515,00\r\n\r\nVALOR DO CONJUNTO TAJ SEM PUFF R\$6.144,00",
                'valor' => '6144',
                'valor_promocional' => null,
                'slug' => 'namoradeira-taj-trama-vai-e-vem',
                'status' => 1,
                'created_at' => '2025-03-31 20:26:28',
                'updated_at' => '2025-03-31 20:26:28',
            ],
            [
                'id' => 22,
                'categoria_id' => 5,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67eafaf2bebaf-collect-31-03-25-.svg',
                'titulo' => 'NAMORADEIRA TAJ - TRAMA "X"',
                'descricao' => "DESCRIÇÃO\r\n\r\nNAMORADEIRA TAJ TRAMA \"X\" CN\r\nLARGURA TOTAL - 1,30M\r\nLARGURA DO ACENTO - 1,20M\r\nPROFUNDIDADE TOTAL - 0,65M\r\nPROFUNDIDADE DO ACENTO - 0,58M\r\nALTURA DO ACENTO 0,43M\r\nR\$2.910,00\r\n\r\nPOLTRONA TAJ TRAMA 'X' CORDA NAUTICA\r\nLARGURA TOTAL - 0,65M\r\nLARGURA DO ACENTO - 0,55M\r\nPROFUNDIDADE TOTAL - 0,65M\r\nPROFUNDIDADE DO ACENTO - 0,58M\r\nALTURA DO ACENTO - 0,43M\r\nR\$1.810,00\r\n\r\nPUFF GARDEN ILHA BELA CORDA NAUTICA \r\nDIAMETRO TOTAL - 0,40M\r\nALTURA TOTAL - 0,40M\r\nR\$890,00\r\n\r\nPUFF GARDEN COMEIA\r\nDIAMETRO TOTAL - 0,40M\r\nALTURA TOTAL - 0,40M\r\nR\$1.120,00\r\n\r\nVALOR DO CONJUNTO TAJ SEM PUFF R\$6.530,00",
                'valor' => '6530',
                'valor_promocional' => null,
                'slug' => 'namoradeira-taj-trama-x',
                'status' => 1,
                'created_at' => '2025-03-31 20:28:34',
                'updated_at' => '2025-03-31 20:28:34',
            ],
            [
                'id' => 23,
                'categoria_id' => 5,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67eafb6ae5790-collect-31-03-25-.svg',
                'titulo' => 'SOFÁ MACRAME',
                'descricao' => "DESCRIÇÃO\r\n\r\nSOFÁ MACRAME EM CORDA NAUTICA\r\nLARGURA TOTAL - 1,80M\r\nLARGURA DO ACENTO - 1,75M\r\nALTURA DO ACENTO - 0,45M\r\nPROFUNDIDADE TOTAL - 0,78M\r\nPROFUNDIDADE DO ACENTO - 0,70M\r\nR\$4.500,00\r\n\r\nPOLTRONA MACRAME CORDA NAUTICA\r\nLARGURA TOTAL - 0,75M\r\nLARGURA DO ACENTO - 0,70M\r\nALTURA DO ACENTO - 0,45M\r\nPROFUNDIDADE TOTAL - 0,78M\r\nPROFUNDIDADE DO ACENTO - 0,70M\r\nR\$2.589,00\r\n\r\nMESA DE CENTRO MACRAME CORDA NAUTICA\r\nTAMPO EM MADEIRA CUMARU\r\nLARGURA TOTAL - 1,00M\r\nPROFUNDIDADE TOTAL - 1,00M\r\nALTURA TOTAL - 0,45M\r\nR\$3.500,00\r\n\r\nVALOR DO CONJUNTO R\$13.178,00",
                'valor' => '13178',
                'valor_promocional' => null,
                'slug' => 'sofa-macrame',
                'status' => 1,
                'created_at' => '2025-03-31 20:30:34',
                'updated_at' => '2025-03-31 20:30:34',
            ],
            [
                'id' => 24,
                'categoria_id' => 5,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67eafbd7ab71e-collect-31-03-25-.svg',
                'titulo' => 'SOFÁ LAJES',
                'descricao' => "DESCRIÇÃO\r\n\r\nSOFÁ LAJES EM CORDA NAUTICA\r\nLARGURA TOTAL - 2,00M\r\nLARGURA DO ACENTO - 1,60M\r\nALTURA TOTAL - 0,85M\r\nPROFUNDIDADE TOTAL - 1,05M\r\nPROFUNDIDADE DO ACENTO -0,66M\r\nR\$9.315,00\r\n\r\nPOLTRONA LAJES CORDA NAUTICA\r\nLARGURA TOTAL - 1,10M\r\nALTURA TOTAL - 0,85M\r\nPROFUNDIDADE TOTAL - 1,05M\r\nDIAMETRO DO ACENTO - 0,66M\r\nR\$4.644,00\r\n\r\nMESA DE CENTRO FECHADA CORDA NAUTICA 10MM\r\n DIAMETRO TOTAL - 0,70M\r\n ALTURA TOTAL - 0,42M\r\nPOLTRONA LAJES CORDA NAUTICA\r\nDIAMETRO TOTAL - 0,70M\r\nALTURA TOTAL - 0,42M\r\nR\$2.992,00\r\n\r\nVALOR DO CONJUNTO R\$21.595,00",
                'valor' => '21595',
                'valor_promocional' => null,
                'slug' => 'sofa-lajes',
                'status' => 1,
                'created_at' => '2025-03-31 20:32:23',
                'updated_at' => '2025-03-31 20:32:23',
            ],
            [
                'id' => 25,
                'categoria_id' => 5,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67eafc5a11641-collect-31-03-25-.svg',
                'titulo' => 'SOFÁ ROMA',
                'descricao' => "DESCRIÇÃO\r\n\r\nSOFÁ ROMA 4 LUGARES EM CORDA NAUTICA\r\nLARGURA TOTAL - 2,55M\r\nPROFUNDIDADE TOTAL - 1,15M\r\nALTURA DO ACENTO 0,45M\r\nR\$11.240,00\r\n\r\nMODULO SOFÁ ROMA MAIOR\r\nLARGURA TOTAL - 1,50M\r\nPROFUNDIDADE TOTAL - 0,95M\r\nALTURA DO ACENTO - 0,45M\r\nR\$2.940,00\r\n\r\nMODULO SOFÁ ROMA MENOR\r\nLARGURA TOTAL - 1,15M\r\nPROFUNDIDADE TOTAL - 1,20M\r\nALTURA DO ACENTO - 0,45M\r\nR\$2.620,00\r\n\r\nPOLTRONA ROMA CORDA NAUTICA\r\nLARGURA TOTAL - 1,15M\r\nPROFUNDIDADE TOTAL - 1,15M\r\nALTURA DO ACENTO - 0,45M\r\nR\$4.900,00\r\n\r\nVALOR DO CONJUNTO R\$26.600,00",
                'valor' => '26600',
                'valor_promocional' => null,
                'slug' => 'sofa-roma',
                'status' => 1,
                'created_at' => '2025-03-31 20:34:34',
                'updated_at' => '2025-03-31 20:34:34',
            ],
            [
                'id' => 26,
                'categoria_id' => 5,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67eafcd59f4c0-collect-31-03-25-.svg',
                'titulo' => 'SOFÁ AUSTRALIA',
                'descricao' => "DESCRIÇÃO\r\n\r\nSOFÁ AUSTRALIA EM CORDA NAUTICA\r\nLARGURA TOTAL - 1,80M\r\nPROFUNDIDADE TOTAL - 0,78M\r\nPROFUNDIDADE DO ACENTO - 0,70M\r\nALTURA DO ACENTO 0,45M\r\nR\$4.110,00\r\n\r\nPOLTRONA AUSTRALIA CORDA NAUTICA\r\nLARGURA TOTAL - 0,75M\r\nPROFUNDIDADE TOTAL - 0,78M\r\nPROFUNDIDADE DO ACENTO - 0,70M\r\nALTURA DO ACENTO - 0,45M\r\nR\$2.250,00\r\n\r\nCHAMPANHEIRA TRAMA FECHADA CORDA NAUTICA 10MM\r\nDIAMETRO TOTAL - 0,70M\r\nALTURA TOTAL - 0,37M\r\nR\$3.260,00\r\n\r\nVALOR DO CONJUNTO R\$11.870,00",
                'valor' => '11870',
                'valor_promocional' => null,
                'slug' => 'sofa-australia',
                'status' => 1,
                'created_at' => '2025-03-31 20:36:37',
                'updated_at' => '2025-03-31 20:36:37',
            ],
            [
                'id' => 27,
                'categoria_id' => 5,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67eafd3b0a918-collect-31-03-25-.svg',
                'titulo' => 'SOFÁ MILLENIUM',
                'descricao' => "DESCRIÇÃO\r\n\r\nSOFÁ MILLENIUM EM CORDA NAUTICA\r\nLARGURA TOTAL - 2,00M\r\nPROFUNDIDADE TOTAL - 0,75M\r\nPROFUNDIDADE DO ACENTO - 0,70M\r\nALTURA DO ACENTO 0,37M\r\nR\$7.160,00\r\n\r\nPOLTRONA MILLENIUM CORDA NAUTICA\r\nLARGURA TOTAL - 0,75M\r\nPROFUNDIDADE TOTAL - 0,75M\r\nPROFUNDIDADE DO ACENTO - 0,70M\r\nALTURA DO ACENTO - 0,37M\r\nR\$3.695,00\r\n\r\nCHAMPANHEIRA TRAMA FECHADA CORDA NAUTICA 6MM\r\nDIAMETRO TOTAL - 0,70M\r\nALTURA TOTAL - 0,37M\r\nR\$3.280,00\r\n\r\nVALOR DO CONJUNTO R\$17.830,00",
                'valor' => '17830',
                'valor_promocional' => null,
                'slug' => 'sofa-millenium',
                'status' => 1,
                'created_at' => '2025-03-31 20:38:19',
                'updated_at' => '2025-03-31 20:38:19',
            ],
            [
                'id' => 28,
                'categoria_id' => 5,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67eafecd9793f-collect-31-03-25-.svg',
                'titulo' => 'CONJUNTO DE SOFÁ CANADÁ',
                'descricao' => "DESCRIÇÃO\r\n\r\nCONJUNTO DE SOFÁ CANADÁ\r\nTODOS OS MÓDULOS TEM A DIMENSÃO DE:\r\nLARGURA TOTAL = 1,00M\r\nPROFUNDIDADE TOTAL = 1,00M\r\nVALOR MODOLO COM ESTOFADO E ENCOSTO 4 UNIDADES \r\n(VALOR POR UNIDADE : R\$5.850,00)\r\n\r\nVALOR MODULO COM ESTOFADO SEM ENCOSTO 1 UNIDADE \r\nR\$4.600,00\r\n\r\nVALOR MODULO SEM ESTOFADO 2 UNIDADES\r\n(VALOR POR UNIDADE: R\$3.100,00)\r\n\r\nVALOR DO CONJUNTO R\$34.200,00",
                'valor' => '34200',
                'valor_promocional' => null,
                'slug' => 'conjunto-de-sofa-canada',
                'status' => 1,
                'created_at' => '2025-03-31 20:45:01',
                'updated_at' => '2025-03-31 20:45:01',
            ],
            [
                'id' => 29,
                'categoria_id' => 5,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67eaff3680915-collect-31-03-25-.svg',
                'titulo' => 'SOFÁ ANTARES',
                'descricao' => "DESCRIÇÃO\r\n\r\nSOFÁ ANTARES EM CORDA NAUTICA\r\nLARGURA TOTAL - 1,80M\r\nLARGURA DO ACENTO - 1,75M\r\nALTURA DO ACENTO - 0,41M\r\nPROFUNDIDADE TOTAL - 0,83M\r\nPROFUNDIDADE DO ACENTO - 0,81\r\nR\$5.335,00\r\n\r\nPOLTRONA MACRAME CORDA NAUTICA\r\nLARGURA TOTAL - 0,80M\r\nLARGURA DO ACENTO - 0,75M\r\nALTURA DO ACENTO - 0,41M\r\nPROFUNDIDADE TOTAL - 0,83M\r\nPROFUNDIDADE DO ACENTO - 0,81M\r\nR\$2.760,00\r\n\r\nCHAMPANHEIRA ANTERES CORDA NAÚTICA\r\nDIAMETRO TOTAL - 0,70M\r\nALTURA TOTAL - 0,37M\r\nR\$2.954,00\r\n\r\nVALOR DO CONJUNTO R\$13.809,00",
                'valor' => '13809',
                'valor_promocional' => null,
                'slug' => 'sofa-antares',
                'status' => 1,
                'created_at' => '2025-03-31 20:46:46',
                'updated_at' => '2025-03-31 20:46:46',
            ],
            [
                'id' => 30,
                'categoria_id' => 5,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67eaffa49de56-collect-31-03-25-.svg',
                'titulo' => 'SOFÁ TAILANDIA',
                'descricao' => "DESCRIÇÃO \r\n\r\nSOFÁ TAILANDIA EM CORDA NAUTICA\r\nLARGURA TOTAL - 1,85M\r\nPROFUNDIDADE TOTAL - 0,90M\r\nPROFUNDIDADE DO ACENTO - 0,75M\r\nALTURA DO ACENTO 0,44M\r\nR\$6.950,00\r\n\r\nPOLTRONA TAILANDIA CORDA NAUTICA\r\nLARGURA TOTAL - 0,95M\r\nPROFUNDIDADE TOTAL - 0,90M\r\nPROFUNDIDADE DO ACENTO - 0,75M\r\nALTURA DO ACENTO - 0,44M\r\nR\$3.780,00\r\n\r\nMESA DE CENTRO TAILIANDIA TAMPO EM MARMORE CORDA NAUTICA \r\nDIAMETRO TOTAL - 0,80M\r\nALTURA TOTAL - 0,50M\r\nR\$3.420,00\r\n\r\nVALOR DO CONJUNTO R\$17.930,00",
                'valor' => '17930',
                'valor_promocional' => null,
                'slug' => 'sofa-tailandia',
                'status' => 1,
                'created_at' => '2025-03-31 20:48:36',
                'updated_at' => '2025-03-31 20:48:36',
            ],
            [
                'id' => 31,
                'categoria_id' => 5,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67eb0020ca5ef-collect-31-03-25-.svg',
                'titulo' => 'CONJUNTO MONACO',
                'descricao' => "DESCRIÇÃO\r\n\r\nCONJUNTO MONACO EM TRICÔ NAUTICO\r\nLARGURA TOTAL - 1,50M\r\nLARGURA DO ACENTO - 1,42M\r\nALTURA DO ACENTO - 0,35M\r\nPROFUNDIDADE TOTAL - 0,85M\r\nPROFUNDIDADE DO ACENTO - 0,81M\r\nR\$5.385,00\r\n\r\nPOLTRONA MONACO TRICÔ NAUTICA\r\nLARGURA TOTAL - 0,80M\r\nLARGURA DO ACENTO - 0,73M\r\nALTURA DO ACENTO - 0,35M\r\nPROFUNDIDADE TOTAL - 0,85M\r\nPROFUNDIDADE DO ACENTO - 0,81M\r\nR\$3.670,00\r\n\r\nMESA DE CENTRO MONACO TRICO NAUTICA TAMPO EM MADEIRA CUMARU\r\nLARGURA TOTAL - 1,00M\r\nPROFUNDIDADE TOTAL - 0,65M\r\nALTURA TOTAL - 0,48M\r\nR\$4.240,00\r\n\r\nVALOR DO CONJUNTO R\$16.965,00",
                'valor' => '16965',
                'valor_promocional' => null,
                'slug' => 'conjunto-monaco',
                'status' => 1,
                'created_at' => '2025-03-31 20:50:40',
                'updated_at' => '2025-03-31 20:50:40',
            ],
            [
                'id' => 32,
                'categoria_id' => 5,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67eb005c95f39-collect-31-03-25-.svg',
                'titulo' => 'POLTRONA RAINHA',
                'descricao' => "DESCRIÇÃO\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK\r\nDIMENSÕES:\r\nLARGURA TOTAL - 0,94M\r\nPROFUNDIDA TOTAL - 0,77M\r\nALTURA TOTAL - 1.60M",
                'valor' => '3970',
                'valor_promocional' => null,
                'slug' => 'poltrona-rainha',
                'status' => 1,
                'created_at' => '2025-03-31 20:51:40',
                'updated_at' => '2025-03-31 20:51:40',
            ],
            [
                'id' => 33,
                'categoria_id' => 8,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebc7b2d595b-collect-01-04-25-.svg',
                'titulo' => 'ESPREGUIÇADEIRA ITAPEMA',
                'descricao' => "DESCRIÇÃO\r\n\r\nESPREGUIÇADEIRA ITAPEMA TRICÔ NÁUTICO\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\n\r\nDIMENSÕES:\r\nLARGURA TOTAL - 0,70M\r\nPROFUNDIDADE TOTAL - 1,90M\r\nALTURA TOTAL - 0,30M",
                'valor' => '3390',
                'valor_promocional' => null,
                'slug' => 'espreguicadeira-itapema',
                'status' => 1,
                'created_at' => '2025-04-01 11:02:10',
                'updated_at' => '2025-04-01 11:02:10',
            ],
            [
                'id' => 34,
                'categoria_id' => 8,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebc7ef293f8-collect-01-04-25-.svg',
                'titulo' => 'ESPREGUIÇADEIRA SLING',
                'descricao' => "DESCRIÇÃO\r\n\r\nESPREGUIÇADEIRA EM TELA SLING\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nTECIDO ACQUABLOCK\r\n\r\nDIMENSÕES:\r\nLARGURA TOTAL - 0,65M\r\nPROFUNDIDADE TOTAL - 1,90M\r\nALTURA TOTAL - 0,30M",
                'valor' => '2692',
                'valor_promocional' => null,
                'slug' => 'espreguicadeira-sling',
                'status' => 1,
                'created_at' => '2025-04-01 11:03:11',
                'updated_at' => '2025-04-01 11:03:11',
            ],
            [
                'id' => 35,
                'categoria_id' => 8,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebc82e3dcd9-collect-01-04-25-.svg',
                'titulo' => 'ESPREGUIÇADEIRA BOGOTÁ',
                'descricao' => "DESCRIÇÃO\r\n\r\nESPREGUIÇADEIRA BOGOTÁ TRAMA COMÉIA\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\n\r\nDIMENSÕES:\r\nLARGURA TOTAL - 0,70M\r\nPROFUNDIDADE TOTAL - 1,70M\r\nALTURA TOTAL - 0,68M",
                'valor' => '3299',
                'valor_promocional' => null,
                'slug' => 'espreguicadeira-bogota',
                'status' => 1,
                'created_at' => '2025-04-01 11:04:14',
                'updated_at' => '2025-04-01 11:04:14',
            ],
            [
                'id' => 36,
                'categoria_id' => 8,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebc8708c70d-collect-01-04-25-.svg',
                'titulo' => 'ESPREGUIÇADEIRA GASPAR',
                'descricao' => "DESCRIÇÃO\r\n\r\nESPREGUIÇADEIRA GASPAR TRAMA FECHADA\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\n\r\nCORDA NAUTICA\r\nDIMENSÕES:\r\nLARGURA TOTAL - 0,70M\r\nPROFUNDIDADE TOTAL - 1,90M\r\nALTURA TOTAL - 0,30M",
                'valor' => '3192',
                'valor_promocional' => null,
                'slug' => 'espreguicadeira-gaspar',
                'status' => 1,
                'created_at' => '2025-04-01 11:05:20',
                'updated_at' => '2025-04-01 11:05:20',
            ],
            [
                'id' => 37,
                'categoria_id' => 8,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebc8c2e4ca4-collect-01-04-25-.svg',
                'titulo' => 'ESPREGUIÇADEIRA GASPAR TELINHA',
                'descricao' => "DESCRIÇÃO\r\n\r\nESPREGUIÇADEIRA GASPAR TRAMA TELINHA\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK\r\n\r\nDIMENSÕES:\r\nLARGURA TOTAL - 0,70M\r\nPROFUNDIDADE TOTAL - 1,90M\r\nALTURA TOTAL - 0,30M",
                'valor' => '2417',
                'valor_promocional' => null,
                'slug' => 'espreguicadeira-gaspar-telinha',
                'status' => 1,
                'created_at' => '2025-04-01 11:06:42',
                'updated_at' => '2025-04-01 11:06:42',
            ],
            [
                'id' => 38,
                'categoria_id' => 8,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebc9147408f-collect-01-04-25-.svg',
                'titulo' => 'ESPREGUIÇADEIRA GASPAR S/ BRAÇO',
                'descricao' => "DESCRIÇÃO\r\n\r\nESPREGUIÇADEIRA GASPAR S/ BRAÇO TRAMA TELINHA COM COLCHONETE\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK\r\n\r\nDIMENSÕES:\r\nLARGURA TOTAL - 0,70M\r\nPROFUNDIDADE TOTAL - 1,90M\r\nALTURA TOTAL - 0,30M",
                'valor' => '2798',
                'valor_promocional' => null,
                'slug' => 'espreguicadeira-gaspar-s-braco',
                'status' => 1,
                'created_at' => '2025-04-01 11:08:04',
                'updated_at' => '2025-04-01 11:08:04',
            ],
            [
                'id' => 39,
                'categoria_id' => 8,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebc95233879-collect-01-04-25-.svg',
                'titulo' => 'ESPREGUIÇADEIRA TOPÁZIO',
                'descricao' => "DESCRIÇÃO\r\n\r\nESPREGUIÇADEIRA TOPÁZIO EM CORDA NÁUTICA\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK\r\n\r\nDIMENSÕES:\r\nLARGURA TOTAL - 0,70M\r\nPROFUNDIDADE TOTAL - 1,90M\r\nALTURA TOTAL - 0,30M",
                'valor' => '4667',
                'valor_promocional' => null,
                'slug' => 'espreguicadeira-topazio',
                'status' => 1,
                'created_at' => '2025-04-01 11:09:06',
                'updated_at' => '2025-04-01 11:09:06',
            ],
            [
                'id' => 40,
                'categoria_id' => 8,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebc98f15f11-collect-01-04-25-.svg',
                'titulo' => 'ESPREGUIÇADEIRA BONA',
                'descricao' => "DESCRIÇÃO\r\n\r\nESPREGUIÇADEIRA BONA EM CORDA NÁUTICA\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\n\r\nDIMENSÕES:\r\nLARGURA TOTAL - 0,70M\r\nPROFUNDIDADE TOTAL - 2,00M\r\nALTURA TOTAL - 0,30M",
                'valor' => '2720',
                'valor_promocional' => null,
                'slug' => 'espreguicadeira-bona',
                'status' => 1,
                'created_at' => '2025-04-01 11:10:07',
                'updated_at' => '2025-04-01 11:10:07',
            ],
            [
                'id' => 41,
                'categoria_id' => 8,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebc9c27b073-collect-01-04-25-.svg',
                'titulo' => 'ESPREGUIÇADEIRA MANAUS',
                'descricao' => "DESCRIÇÃO\r\n\r\nESPREGUIÇADEIRA MANAUS TRAMA COMÉIA\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\n\r\nDIMENSÕES:\r\nLARGURA TOTAL - 0,65M\r\nPROFUNDIDADE TOTAL - 1,90M\r\nALTURA TOTAL - 0,30M",
                'valor' => '3149',
                'valor_promocional' => null,
                'slug' => 'espreguicadeira-manaus',
                'status' => 1,
                'created_at' => '2025-04-01 11:10:58',
                'updated_at' => '2025-04-01 11:10:58',
            ],
            [
                'id' => 42,
                'categoria_id' => 8,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebc9f870256-collect-01-04-25-.svg',
                'titulo' => 'ESPREGUIÇADEIRA CAIOBÁ',
                'descricao' => "DESCRIÇÃO\r\n\r\nESPREGUIÇADEIRA CAIOBÁ\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\n\r\nDIMENSÕES:\r\nLARGURA TOTAL - 0,65M\r\nPROFUNDIDADE TOTAL - 1,80M",
                'valor' => '2542',
                'valor_promocional' => null,
                'slug' => 'espreguicadeira-caioba',
                'status' => 1,
                'created_at' => '2025-04-01 11:11:52',
                'updated_at' => '2025-04-01 11:11:52',
            ],
            [
                'id' => 43,
                'categoria_id' => 8,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebca3de071a-collect-01-04-25-.svg',
                'titulo' => 'ESPREGUIÇADEIRA AUSTRÁLIA',
                'descricao' => "DESCRIÇÃO\r\n\r\nESPREGUIÇADEIRA AUSTRÁLIA\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK\r\n\r\nDIMENSÕES:\r\nLARGURA TOTAL -0,70M\r\nPROFUNDIDADE TOTAL - 2,00M \r\nALTURA TOTAL - 0,30M",
                'valor' => '3598',
                'valor_promocional' => null,
                'slug' => 'espreguicadeira-australia',
                'status' => 1,
                'created_at' => '2025-04-01 11:13:01',
                'updated_at' => '2025-04-01 11:13:01',
            ],
            [
                'id' => 44,
                'categoria_id' => 8,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebca6e3941c-collect-01-04-25-.svg',
                'titulo' => 'ESPREGUIÇADEIRA MILLENIUM',
                'descricao' => "DESCRIÇÃO\r\n\r\nESPREGUIÇADEIRA MILLENIUM\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK\r\n\r\nDIMENSÕES:\r\nLARGURA TOTAL - 0,70M\r\nPROFUNDIDADE TOTAL - 2,00M\r\nALTURA TOTAL - 0,30M",
                'valor' => '4667',
                'valor_promocional' => null,
                'slug' => 'espreguicadeira-millenium',
                'status' => 1,
                'created_at' => '2025-04-01 11:13:50',
                'updated_at' => '2025-04-01 11:13:50',
            ],
            [
                'id' => 45,
                'categoria_id' => 7,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebcb16dd90f-collect-01-04-25-.svg',
                'titulo' => 'BALANÇO FOLHA COM SUPORTE',
                'descricao' => "DESCRIÇÃO\r\n\r\nBALANÇO FOLHA COM SUPORTE \"U\"\r\n DIMENSÕES\r\n DIAMETRO TOTAL - 1,10M\r\n PROFUNDIDADE TOTAL - 0,90M\r\n ESPECIFICAÇÕES:\r\n ESTRUTURA EM ALUMINIO\r\n PINTURA ELETROSTATICA\r\n CORDA NAUTICA\r\n TECIDO ACQUABLOCK\r\n\r\nBALANÇO: R\$4.299,00\r\nSUPORTE: R\$1.449,00",
                'valor' => '5748',
                'valor_promocional' => null,
                'slug' => 'balanco-folha-com-suporte',
                'status' => 1,
                'created_at' => '2025-04-01 11:16:38',
                'updated_at' => '2025-04-01 11:16:38',
            ],
            [
                'id' => 46,
                'categoria_id' => 7,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebcb5c4094c-collect-01-04-25-.svg',
                'titulo' => 'BALANÇO MACAIPE',
                'descricao' => "DESCRIÇÃO\r\n\r\nBALANÇO MACAIPE\r\n\r\nDIMENSÕES\r\nDIAMETRO DO ACENTO - 1,20M\r\nALTURA TOTAL - 1,80M\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK",
                'valor' => '7140',
                'valor_promocional' => null,
                'slug' => 'balanco-macaipe',
                'status' => 1,
                'created_at' => '2025-04-01 11:17:48',
                'updated_at' => '2025-04-01 11:17:48',
            ],
            [
                'id' => 47,
                'categoria_id' => 7,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebcba3a4f5c-collect-01-04-25-.svg',
                'titulo' => 'BALANÇO TAJ',
                'descricao' => "DESCRIÇÃO\r\n\r\nBALANÇO TAJ TRAMA \"X\"\r\n\r\nDIMENSÕES\r\nLARGURA TOTAL - 0,65M\r\nLARGURA DO ACENTO - 0,58M\r\nPROFUNDIDADE TOTAL - 0,65M\r\nPROFUNDIDADE DO ACENTO - 0,58M\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK",
                'valor' => '1730',
                'valor_promocional' => null,
                'slug' => 'balanco-taj',
                'status' => 1,
                'created_at' => '2025-04-01 11:18:59',
                'updated_at' => '2025-04-01 11:18:59',
            ],
            [
                'id' => 48,
                'categoria_id' => 7,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebcbeae373c-collect-01-04-25-.svg',
                'titulo' => 'BALANÇO TOKIO',
                'descricao' => "DESCRIÇÃO\r\n\r\nBALANÇO TOKIO\r\n\r\nDIMENSÕES\r\nDIAMETRO TOTAL - 1,10M\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK",
                'valor' => '2852',
                'valor_promocional' => null,
                'slug' => 'balanco-tokio',
                'status' => 1,
                'created_at' => '2025-04-01 11:20:10',
                'updated_at' => '2025-04-01 11:20:10',
            ],
            [
                'id' => 49,
                'categoria_id' => 7,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebcc2c08edb-collect-01-04-25-.svg',
                'titulo' => 'BALANÇO PÊNDULO',
                'descricao' => "DESCRIÇÃO\r\n\r\nDIMENSÕES\r\nDIAMETRO TOTAL - 1,30M\r\nPROFUNDIDADE DO ACENTO - 0,40M\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK",
                'valor' => '2761',
                'valor_promocional' => null,
                'slug' => 'balanco-pendulo',
                'status' => 1,
                'created_at' => '2025-04-01 11:21:16',
                'updated_at' => '2025-04-01 11:21:16',
            ],
            [
                'id' => 50,
                'categoria_id' => 7,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebcc602d18e-collect-01-04-25-.svg',
                'titulo' => 'BALANÇO ÍNDIA',
                'descricao' => "DESCRIÇÃO\r\n\r\nBALANÇO ÍNDIA\r\n\r\nDIMENSÕES\r\nDIAMETRO DO ACENTO -  1,72M\r\nALTURA TOTAL - 2,40M\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK",
                'valor' => '11350',
                'valor_promocional' => null,
                'slug' => 'balanco-india',
                'status' => 1,
                'created_at' => '2025-04-01 11:22:08',
                'updated_at' => '2025-04-01 11:22:08',
            ],
            [
                'id' => 51,
                'categoria_id' => 7,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebcca19fb33-collect-01-04-25-.svg',
                'titulo' => 'BALANÇO PÉROLA',
                'descricao' => "DESCRIÇÃO\r\n\r\nBALANÇO PÉROLA\r\n\r\nDIMENSÕES\r\nDIAMETRO TOTAL - 1,10M\r\nPROFUNDIDADE TOTAL - 0,90M\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK",
                'valor' => '3265',
                'valor_promocional' => null,
                'slug' => 'balanco-perola',
                'status' => 1,
                'created_at' => '2025-04-01 11:23:13',
                'updated_at' => '2025-04-01 11:23:13',
            ],
            [
                'id' => 52,
                'categoria_id' => 7,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebcd480836f-collect-01-04-25-.svg',
                'titulo' => 'BALANÇO GOTA COM SUPORTE',
                'descricao' => "DESCRIÇÃO\r\n\r\nBALANÇO GOTA COM SUPORTE BASE REDONDA\r\n\r\nDIMENSÕES\r\nLAGURA TOTAL - 1,10M\r\nALTURA TOTAL - 1,50M\r\nPROFUNDIDADE TOTAL -0,80\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK\r\n\r\nBALANÇO: R\$3.549,00\r\nSUPORTE: R\$1.565,00",
                'valor' => '5114',
                'valor_promocional' => null,
                'slug' => 'balanco-gota-com-suporte',
                'status' => 1,
                'created_at' => '2025-04-01 11:26:00',
                'updated_at' => '2025-04-01 11:26:00',
            ],
            [
                'id' => 53,
                'categoria_id' => 7,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebcd874fe6b-collect-01-04-25-.svg',
                'titulo' => 'BALANÇO EXCLUSIVO',
                'descricao' => "DESCRIÇÃO\r\n\r\nBALANÇO EXCLUSIVO\r\n\r\nDIMENSÕES\r\nLARGURA TOTAL - 0,80M\r\nLARGURA DO ACENTO - 0,75M\r\nPROFUNDIDADE TOTAL - 0,80M\r\nPROFUNDIDADE DO ACENTO - 0,80\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK",
                'valor' => '2550',
                'valor_promocional' => null,
                'slug' => 'balanco-exclusivo',
                'status' => 1,
                'created_at' => '2025-04-01 11:27:03',
                'updated_at' => '2025-04-01 11:27:03',
            ],
            [
                'id' => 54,
                'categoria_id' => 7,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebcdb1d1982-collect-01-04-25-.svg',
                'titulo' => 'BALANÇO ROMEU',
                'descricao' => "DESCRIÇÃO\r\n\r\nBALANÇO ROMEU\r\n\r\nDIMENSÕES\r\nALTURA TOTAL - 1,20\r\nLARGURA TOTAL - 1,00\r\nPROFUNIDADE TOTAL - 0,80\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK",
                'valor' => '3652',
                'valor_promocional' => null,
                'slug' => 'balanco-romeu',
                'status' => 1,
                'created_at' => '2025-04-01 11:27:45',
                'updated_at' => '2025-04-01 11:27:45',
            ],
            [
                'id' => 55,
                'categoria_id' => 6,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebcdfd0df69-collect-01-04-25-.svg',
                'titulo' => 'BANQUETA MINAS',
                'descricao' => "DESCRIÇÃO\r\n\r\nBANQUETA MINAS EM CORDA NÁUTICA\r\n\r\nDIMENSÕES\r\nALTURA TOTAL - 1,10M\r\nALTURA DO ACENTO - 0,70M\r\nLARGURA TOTAL - 0,63M\r\nLARGURA DO ACENTO - 0,50\r\nPROFUNDIDADE TOTAL - 0,65M\r\nPROFUNDIDADE DO ACENTO - 0,45M\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA",
                'valor' => '959',
                'valor_promocional' => null,
                'slug' => 'banqueta-minas',
                'status' => 1,
                'created_at' => '2025-04-01 11:29:01',
                'updated_at' => '2025-04-01 11:29:01',
            ],
            [
                'id' => 56,
                'categoria_id' => 6,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebce42a648c-collect-01-04-25-.svg',
                'titulo' => 'BANQUETA GEÓRGIA',
                'descricao' => "DESCRIÇÃO\r\n\r\nBANQUETA GEÓRGIA EM CORDA NÁUTICA\r\n\r\nDIMENSÕES\r\nALTURA TOTAL - 1,05M\r\nALTURA DO ACENTO - 0,70M\r\nLARGURA TOTAL - 0,50M\r\nLARGURA DO ACENTO - 0,45M\r\nPROFUNDIDADE TOTAL - 0,50M\r\nPROFUNDIDADE DO ACENTO - 0,45M\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nMADEIRA CUMARU",
                'valor' => '899',
                'valor_promocional' => null,
                'slug' => 'banqueta-georgia',
                'status' => 1,
                'created_at' => '2025-04-01 11:30:10',
                'updated_at' => '2025-04-01 11:30:10',
            ],
            [
                'id' => 57,
                'categoria_id' => 6,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebce7809e68-collect-01-04-25-.svg',
                'titulo' => 'BANQUETA MIAMI',
                'descricao' => "DESCRIÇÃO\r\n\r\nBANQUETA MIAMI EM CORDA NÁUTICA\r\n\r\nDIMENSÕES\r\nALTURA TOTAL - 1,10M\r\nALTURA DO ACENTO - 0,70M\r\nLARGURA TOTAL - 0,60M\r\nLARGURA DO ACENTO - 0,50M\r\nPROFUNDIDADE TOTAL - 0,55M\r\nPROFUNDIDADE DO ACENTO - 0,45M\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nMADEIRA CUMARU",
                'valor' => '995',
                'valor_promocional' => null,
                'slug' => 'banqueta-miami',
                'status' => 1,
                'created_at' => '2025-04-01 11:31:04',
                'updated_at' => '2025-04-01 11:31:04',
            ],
            [
                'id' => 58,
                'categoria_id' => 6,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd013c6cdb-collect-01-04-25-.svg',
                'titulo' => 'CONJUNTO BANQUETA BALI TELINHA E BISTRO',
                'descricao' => "DESCRIÇÃO\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK\r\n\r\nBANQUETA BALI TRAMA TELINHA\r\nDIMENSÕES\r\nALTURA TOTAL - 1,09M\r\nALTURA DO ACENTO - 0,75M\r\nLARGURA TOTAL - 0,55M\r\nLARGURA DO ACENTO - 0,46M\r\nPROFUNDIDADE TOTAL - 0,52M\r\nPROFUNDIDADE DO ACENTO - 0,46M\r\nVALOR UNIDADE: R\$1.061,00\r\n\r\nBISTRO BALI TAMPO CUMARU PIZZA\r\nDIAMETRO TOTAL - 0,70M\r\nALTURA TOTAL - 1,02M\r\nVALOR UNIDADE: R\$2.635,00",
                'valor' => '3696',
                'valor_promocional' => null,
                'slug' => 'conjunto-banqueta-bali-telinha-e-bistro',
                'status' => 1,
                'created_at' => '2025-04-01 11:37:55',
                'updated_at' => '2025-04-01 11:37:55',
            ],
            [
                'id' => 59,
                'categoria_id' => 6,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd0c86a257-collect-01-04-25-.svg',
                'titulo' => 'CONJUNTO BANQUETA BALI VAI-VEM E BISTRÔ',
                'descricao' => "DESCRIÇÃO\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK\r\n\r\nBANQUETA BALI TRAMA VAI-VEM\r\nDIMENSÕES\r\nALTURA TOTAL - 1,09M\r\nALTURA DO ACENTO - 0,75M\r\nLARGURA TOTAL - 0,55M\r\nLARGURA DO ACENTO - 0,46M\r\nPROFUNDIDADE TOTAL - 0,52M\r\nPROFUNDIDADE DO ACENTO - 0,46M\r\nVALOR UNIDADE: R\$1.005,00\r\n\r\nBISTRÔ BALI TAMPO CUMARU RIPADO\r\nDIAMETRO TOTAL - 0,70M\r\nALTURA TOTAL - 1,02M\r\nVALOR UNIDADE: R\$2.260,00",
                'valor' => '3265',
                'valor_promocional' => null,
                'slug' => 'conjunto-banqueta-bali-vai-vem-e-bistro',
                'status' => 1,
                'created_at' => '2025-04-01 11:40:56',
                'updated_at' => '2025-04-01 11:40:56',
            ],
            [
                'id' => 60,
                'categoria_id' => 6,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd159137a8-collect-01-04-25-.svg',
                'titulo' => 'CONJUNTO BANQUETA PALHOÇA E BISTRÔ',
                'descricao' => "DESCRIÇÃO\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\n\r\nBANQUETA PALHOÇA TRAMA TELINHA\r\nDIMENSÕES\r\n(L.T=0,40 / A.A=0,70 / A.T=1,06 / P.A=0,40)\r\nLARGURA TOTAL - 0,40M\r\nALTURA TOTAL - 1,06M\r\nALTURA DO ACENTO - 0,70M\r\nPROFUNDIDADE DO ACENTO - 0,40M\r\nVALOR UNIDADE: R\$804,00\r\n\r\nBISTRÔ RIPADO ALUMINIO \r\nALTURA TOTAL 1,00M\r\nDIAMETRO TOTAL - 0,70M\r\nVALOR UNIDADE: R\$1.985",
                'valor' => '2789',
                'valor_promocional' => null,
                'slug' => 'conjunto-banqueta-palhoca-e-bistro',
                'status' => 1,
                'created_at' => '2025-04-01 11:43:21',
                'updated_at' => '2025-04-01 11:43:21',
            ],
            [
                'id' => 61,
                'categoria_id' => 6,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd1ab990ff-collect-01-04-25-.svg',
                'titulo' => 'BANQUETA BELA',
                'descricao' => "DESCRIÇÃO\r\n\r\nBANQUETA BELA TRAMA VAI-VEM\r\n\r\nDIMENSÕES\r\nLARGURA TOTAL - 0,40M\r\nPROFUNDIDADE DO ACENTO  - 0,40M\r\nALTURA DO ACENTO - 0,75M\r\nALTURA TOTAL - 1,06M\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA",
                'valor' => '639',
                'valor_promocional' => null,
                'slug' => 'banqueta-bela',
                'status' => 1,
                'created_at' => '2025-04-01 11:44:43',
                'updated_at' => '2025-04-01 11:44:43',
            ],
            [
                'id' => 62,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd26ece2f3-collect-01-04-25-.svg',
                'titulo' => 'CADEIRA BALI VAI-VEM',
                'descricao' => "DESCRIÇÃO\r\n\r\nCADEIRA BALI TRAMA VAI-VEM\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK\r\n\r\nDIMENSÕES\r\nALTURA TOTAL = 0,75 \r\nALTURA DO ACENTO = 0,41 \r\nLARGURA TOTAL = 0,54\r\nPROFUNDIDADE TOTAL = 0,61\r\nPROFUNDIDADE DO ACENTO = 0,47",
                'valor' => '960',
                'valor_promocional' => null,
                'slug' => 'cadeira-bali-vai-vem',
                'status' => 1,
                'created_at' => '2025-04-01 11:47:58',
                'updated_at' => '2025-04-01 11:47:58',
            ],
            [
                'id' => 63,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd2a035e7b-collect-01-04-25-.svg',
                'titulo' => 'CADEIRA BALI TELINHA',
                'descricao' => "DESCRIÇÃO\r\n\r\nCADEIRA BALI TRAMA TELINHA\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK\r\n\r\nDIMENSÕES\r\nALTURA TOTAL = 0,75 \r\nALTURA DO ACENTO =0 ,41 \r\nLARGURA TOTAL = 0,54\r\nPROFUNDIDADE TOTAL = 0,61\r\nPROFUNDIDADE DO ACENTO = 0,47",
                'valor' => '1020',
                'valor_promocional' => null,
                'slug' => 'cadeira-bali-telinha',
                'status' => 1,
                'created_at' => '2025-04-01 11:48:48',
                'updated_at' => '2025-04-01 11:48:48',
            ],
            [
                'id' => 64,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd2e6796e1-collect-01-04-25-.svg',
                'titulo' => 'CADEIRA PALHOÇA',
                'descricao' => "DESCRIÇÃO\r\n\r\nCADEIRA PALHOÇA TRAMA TELINHA\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\n\r\nDIMENSÕES\r\nALTURA TOTAL = 0,95 \r\nALTURA TOTAL= 0,47 \r\nLARGURA TOTAL = 0,47\r\nPROFUNDIDADE TOTAL = 0,54\r\nPROFUNDIDADE DO ACENTO = 0,44",
                'valor' => '940',
                'valor_promocional' => null,
                'slug' => 'cadeira-palhoca',
                'status' => 1,
                'created_at' => '2025-04-01 11:49:58',
                'updated_at' => '2025-04-01 11:49:58',
            ],
            [
                'id' => 65,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd36d703d4-collect-01-04-25-.svg',
                'titulo' => 'CADEIRA ITUANO',
                'descricao' => "DESCRIÇÃO\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\n\r\nDIMENSÕES\r\nPROFUNDIDADE TOTAL = 0,62\r\nPROFUNDIDADE DO ACENTO = 0,45\r\nLARGURA DO ACENTO = 0,45\r\nALTURA TOTAL = 0,97\r\nALTURA DO ACENTO = 0,45",
                'valor' => '734',
                'valor_promocional' => null,
                'slug' => 'cadeira-ituano',
                'status' => 1,
                'created_at' => '2025-04-01 11:52:13',
                'updated_at' => '2025-04-01 11:52:13',
            ],
            [
                'id' => 66,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd3a6a0471-collect-01-04-25-.svg',
                'titulo' => 'CADEIRA LUZ',
                'descricao' => "DESCRIÇÃO\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\n\r\nDIMENSÕES\r\nALTURA TOTAL = 0,84\r\nALTURA DO ACENTRO = 0,45\r\nPROFUNDIDADE TOTAL = 0,73\r\nPROFUNDIDADE DO ACENTO = 0,42\r\nLARGURA TOTAL = 0,80\r\nLARGURA DO ACENTO = 0,42",
                'valor' => '961',
                'valor_promocional' => null,
                'slug' => 'cadeira-luz',
                'status' => 1,
                'created_at' => '2025-04-01 11:53:10',
                'updated_at' => '2025-04-01 11:53:10',
            ],
            [
                'id' => 67,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd3cf30fa1-collect-01-04-25-.svg',
                'titulo' => 'CADEIRA MADRI',
                'descricao' => "DESCRIÇÃO\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\n\r\nDIMENSÕES\r\nPROFUNDIDADE TOTAL = 0,65\r\nPROFUNDIDADE DO ACENTO = 0,45\r\nALTURA TOTAL = 0,88\r\nALTURA DO ACENTO = 0,43\r\nLARGURA TOTAL = 0,55 \r\nLARGURA DO ACENTO = 0,45",
                'valor' => '833',
                'valor_promocional' => null,
                'slug' => 'cadeira-madri',
                'status' => 1,
                'created_at' => '2025-04-01 11:53:51',
                'updated_at' => '2025-04-01 11:53:51',
            ],
            [
                'id' => 68,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd40b65f1c-collect-01-04-25-.svg',
                'titulo' => 'CADEIRA MARÍLIA',
                'descricao' => "DESCRIÇÃO\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK\r\n\r\nDIMENSÕES\r\nALTURA TOTAL = 0,80\r\nALTURA DO ACENTO = 0,41 \r\nPROFUNDIDADE TOTAL = 0,51 \r\nPROFUNFIDADE DO ACENTO = 0,44\r\nLARGURA TOTAL = 0,61 \r\nLARGURA DO ACENTO = 0,48",
                'valor' => '1060',
                'valor_promocional' => null,
                'slug' => 'cadeira-marilia',
                'status' => 1,
                'created_at' => '2025-04-01 11:54:51',
                'updated_at' => '2025-04-01 11:54:51',
            ],
            [
                'id' => 69,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd434d75c7-collect-01-04-25-.svg',
                'titulo' => 'CADEIRA MINAS',
                'descricao' => "DESCRIÇÃO\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\n\r\nDIMENSÕES\r\nALTURA TOTAL = 0,84M\r\nALTURA DO ACENTO = 0,45M\r\nLARGURA DO ACENTO = 0,50M\r\nLARGURA TOTAL = 0,63M\r\nPROFUNDIDADE DO ACENTO = 0,45M\r\nPROFUNDIDADE TOTAL = 0,65M",
                'valor' => '960',
                'valor_promocional' => null,
                'slug' => 'cadeira-minas',
                'status' => 1,
                'created_at' => '2025-04-01 11:55:32',
                'updated_at' => '2025-04-01 11:55:32',
            ],
            [
                'id' => 70,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd4568d40e-collect-01-04-25-.svg',
                'titulo' => 'CADEIRA BAHAMAS',
                'descricao' => "DESCRIÇÃO\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA",
                'valor' => '918',
                'valor_promocional' => null,
                'slug' => 'cadeira-bahamas',
                'status' => 1,
                'created_at' => '2025-04-01 11:56:06',
                'updated_at' => '2025-04-01 11:56:06',
            ],
            [
                'id' => 71,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd48967bd8-collect-01-04-25-.svg',
                'titulo' => 'CADEIRA FLÓRIDA',
                'descricao' => "DESCRIÇÃO\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nBRAÇO EM CUMARU \r\n\r\nDIMENSÕES:\r\nLARGURA TOTAL - 0,55M\r\nPROFUNDIDA TOTAL - 0,55M\r\nALTURA TOTAL - 0,90M",
                'valor' => '1137',
                'valor_promocional' => null,
                'slug' => 'cadeira-florida',
                'status' => 1,
                'created_at' => '2025-04-01 11:56:57',
                'updated_at' => '2025-04-01 11:56:57',
            ],
            [
                'id' => 72,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd4f9ea2ef-collect-01-04-25-.svg',
                'titulo' => 'CADEIRA MILLENIUM',
                'descricao' => "DESCRIÇÃO\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA \r\nPÉ EM MADEIRA CUMARU\r\nTECIDO ACQUABLOCK\r\n\r\nDIMENSÕES\r\nALTURA TOTAL = 0,93\r\nALTURA DO ACENTO = 0,45\r\nLARGURA TOTAL = 0,68\r\nPROFUNDIDADE DO ACENTO = 0,44\r\nPROFUNDIDADE TOTAL = 0,68",
                'valor' => '2978',
                'valor_promocional' => null,
                'slug' => 'cadeira-millenium',
                'status' => 1,
                'created_at' => '2025-04-01 11:58:49',
                'updated_at' => '2025-04-01 11:58:49',
            ],
            [
                'id' => 73,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd51faf081-collect-01-04-25-.svg',
                'titulo' => 'CADEIRA RAINHA',
                'descricao' => "DESCRIÇÃO\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK",
                'valor' => '2096',
                'valor_promocional' => null,
                'slug' => 'cadeira-rainha',
                'status' => 1,
                'created_at' => '2025-04-01 11:59:27',
                'updated_at' => '2025-04-01 11:59:27',
            ],
            [
                'id' => 74,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd57ed1137-collect-01-04-25-.svg',
                'titulo' => 'CADEIRA MARESIA',
                'descricao' => "DESCRIÇÃO\r\n\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK\r\n\r\nDIMENSÕES:\r\nLARGURA TOTAL - 0,62M\r\nALTURA TOTAL - 0,95M\r\nPROFUNDIDADE TOTAL - 0,70M",
                'valor' => '2045',
                'valor_promocional' => null,
                'slug' => 'cadeira-maresia',
                'status' => 1,
                'created_at' => '2025-04-01 12:01:02',
                'updated_at' => '2025-04-01 12:01:02',
            ],
            [
                'id' => 75,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd620d2eb2-collect-01-04-25-.svg',
                'titulo' => 'CONJUNTO DE MESA PORTUGAL',
                'descricao' => "DESCRIÇÃO\r\n\r\nCONJUNTO DE MESA PORTUGAL TAMPO CUMARU RIPADO COM CADEIRA BALI TRAMA TELINHA\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTAMPO EM MADEIRA CUMARU\r\n\r\nMESA PORTUGAL TAMPO CUMARU RIPADO 2,20M\r\nVALOR UNIDADE: R\$7.552,00\r\n\r\nCADEIRA BALI TRAMA TELINHA\r\nVALOR UNIDADE: R\$1.020,00",
                'valor' => '15712',
                'valor_promocional' => null,
                'slug' => 'conjunto-de-mesa-portugal',
                'status' => 1,
                'created_at' => '2025-04-01 12:03:44',
                'updated_at' => '2025-04-01 12:03:44',
            ],
            [
                'id' => 76,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd6915fd8a-collect-01-04-25-.svg',
                'titulo' => 'CONJUNTO DE MESA ITÁLIA',
                'descricao' => "DESCRIÇÃO\r\n\r\nCONJUNTO MESA ITALIA TAMPO PRANCHA ORGÂNICA COM CADEIRA BH\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA E TRICÔ NAUTICO\r\nTAMPO EM MADEIRA ORGÂNICA\r\n\r\nMESA ITALIA 2,60M TAMPO PRANCHA\r\nVALOR UNIDADE: R\$12.766,00\r\n\r\nCADEIRA BH\r\nVALOR UNIDADE: R\$942,00",
                'valor' => '20302',
                'valor_promocional' => null,
                'slug' => 'conjunto-de-mesa-italia',
                'status' => 1,
                'created_at' => '2025-04-01 12:05:37',
                'updated_at' => '2025-04-01 12:05:37',
            ],
            [
                'id' => 77,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd6feebf1b-collect-01-04-25-.svg',
                'titulo' => 'CONJUNTO DE MESA HOLANDA',
                'descricao' => "DESCRIÇÃO\r\n\r\nCONJUNTO DE MESA HOLANDA TAMPO PRANCHA ORGANICA COM CADEIRA FLORIPA\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTAMPO EM MADEIRA ORGÂNICA\r\n\r\n\r\nMESA HOLANDA TAMPO PRANCHA ORGANICA 2,60M\r\nVALOR UNIDADE: R\$14.040,00\r\n\r\nCADEIRA FLORIPA CORDA NAUTICA\r\nVALOR UNIDADE: R\$795,00",
                'valor' => '18810',
                'valor_promocional' => null,
                'slug' => 'conjunto-de-mesa-holanda',
                'status' => 1,
                'created_at' => '2025-04-01 12:07:26',
                'updated_at' => '2025-04-01 12:07:26',
            ],
            [
                'id' => 78,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd76baf7b5-collect-01-04-25-.svg',
                'titulo' => 'CONJUNTO DE MESA BARCELONA',
                'descricao' => "DESCRIÇÃO\r\n\r\nCONJUNTO DE MESA BARCELONA COM CADEIRA MÔNACO\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK\r\n\r\nMESA BARCELONA TAMPO CUMARU PIZZA 1,20M CENTRO GIRATÓRIO EM ALUMÍNIO\r\nVALOR UNIDADE: R\$5.545,00\r\n\r\nCADEIRA MONACO TRICÔ NÁUTCIO\r\nR\$1.390,00",
                'valor' => '11105',
                'valor_promocional' => null,
                'slug' => 'conjunto-de-mesa-barcelona',
                'status' => 1,
                'created_at' => '2025-04-01 12:09:15',
                'updated_at' => '2025-04-01 12:09:15',
            ],
            [
                'id' => 79,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd7da031aa-collect-01-04-25-.svg',
                'titulo' => 'CONJUNTO DE MESA BASE EM "X"',
                'descricao' => "DESCRIÇÃO\r\n\r\nCONJUNTO DE MESA BASE EM ‘’X’’ COM CADEIRA BH\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK\r\n\r\nMESA BASE ‘’X’’ TAMPO CUMARU PIZZA 1,40M CENTRO GIRATÓRIO\r\nVALOR UNIDADE: R\$7.890,00\r\n\r\nCADEIRA BH  ENCOSTO NO TRICÔ NÁUTICO E ACENTO NA CORDA NÁUTICA\r\nVALOR UNIDADE: R\$942,00",
                'valor' => '13542',
                'valor_promocional' => null,
                'slug' => 'conjunto-de-mesa-base-em-x',
                'status' => 1,
                'created_at' => '2025-04-01 12:11:06',
                'updated_at' => '2025-04-01 12:11:06',
            ],
            [
                'id' => 80,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd847283fa-collect-01-04-25-.svg',
                'titulo' => 'CONJUNTO DE MESA MILLENIUM',
                'descricao' => "DESCRIÇÃO\r\n\r\nCONJUNTO DE MESA MILLENIUM\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK\r\n\r\nMESA BARCELONA TAMPO PIZZA DIÂMETRO 1,50M GIRATORIO SUPERIOR 0,70M\r\nVALOR UNIDADE: 8.243,00\r\n\r\nCADEIRA MILLENIUM\r\nVALOR UNIDADE: R\$2.978,00",
                'valor' => '26111',
                'valor_promocional' => null,
                'slug' => 'conjunto-de-mesa-millenium',
                'status' => 1,
                'created_at' => '2025-04-01 12:12:55',
                'updated_at' => '2025-04-01 12:12:55',
            ],
            [
                'id' => 81,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd8b30685e-collect-01-04-25-.svg',
                'titulo' => 'CONJUNTO DE MESA BALI',
                'descricao' => "DESCRIÇÃO\r\n\r\nCONJUNTO DE MESA BALI TRAMA TELINHA\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK\r\n\r\nMESA BARCELONA TAMPO RIPADO 1,20M\r\nVALOR UNIDADE: R\$3.365,00\r\n\r\nCADEIRA BALI TRAMA TELINHA\r\nVALOR UNIDADE: R\$1.020,00",
                'valor' => '7445',
                'valor_promocional' => null,
                'slug' => 'conjunto-de-mesa-bali',
                'status' => 1,
                'created_at' => '2025-04-01 12:14:43',
                'updated_at' => '2025-04-01 12:14:43',
            ],
            [
                'id' => 82,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd91960ce4-collect-01-04-25-.svg',
                'titulo' => 'CONJUNTO DE MESA FLÓRIDA',
                'descricao' => "DESCRIÇÃO\r\n\r\nCONJUNTO DE MESA FLÓRIDA\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\n\r\nMESA BALI TAMPO EM VIDRO  DIAMETRO 1,20M\r\nVALOR UNIDADE: R\$2.303,00\r\n\r\nCADEIRA FLORIDA TRAMA TELINHA\r\nR\$989,00",
                'valor' => '6259',
                'valor_promocional' => null,
                'slug' => 'conjunto-de-mesa-florida',
                'status' => 1,
                'created_at' => '2025-04-01 12:16:25',
                'updated_at' => '2025-04-01 12:16:25',
            ],
            [
                'id' => 83,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebd96360d38-collect-01-04-25-.svg',
                'titulo' => 'CONJUNTO DE MESA ITUANO',
                'descricao' => "DESCRIÇÃO\r\n\r\nCONJUNTO DE MESA ITUANO\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\n\r\nMESA ALUMINIO DIAMETRO 1,00M\r\nVALOR UNIDADE: R\$1.675,00\r\n\r\nCADEIRA ITUANO\r\nVALOR UNIDADE: R\$734,00",
                'valor' => '4611',
                'valor_promocional' => null,
                'slug' => 'conjunto-de-mesa-ituano',
                'status' => 1,
                'created_at' => '2025-04-01 12:17:39',
                'updated_at' => '2025-04-01 12:17:39',
            ],
            [
                'id' => 84,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebdb91ea699-collect-01-04-25-.svg',
                'titulo' => 'CONJUNTO DE MESA TURIM',
                'descricao' => "DESCRIÇÃO\r\n\r\nCONJUNTO DE MESA TURIM TELINHA\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NÁUTICA\r\nTECIDO ACQUABLOCK\r\n\r\nMESA TURIM TAMPO CUMARU PIZZA DIAMETRO 1,20M\r\nVALOR UNIDADE: R\$5.190,00\r\n\r\nCADEIRA BALI TRAMA TELINHA\r\nVALOR UNIDADE: R\$1.020,00",
                'valor' => '9270',
                'valor_promocional' => null,
                'slug' => 'conjunto-de-mesa-turim',
                'status' => 1,
                'created_at' => '2025-04-01 12:26:57',
                'updated_at' => '2025-04-01 12:26:57',
            ],
            [
                'id' => 85,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebdc09ddaee-collect-01-04-25-.svg',
                'titulo' => 'CONJUNTO DE MESA BALI TELINHA',
                'descricao' => "DESCRIÇÃO\r\n\r\nCONJUNTO DE MESA BALI TRAMA TELINHA\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NÁUTICA\r\nTECIDO ACQUABLOCK\r\n\r\nMESA BALI TAMPO CUMARU PIZZA DIAMETRO 1,20M\r\nVALOR UNIDADE: R\$5.040,00\r\n\r\nCADEIRA BALI TRAMA TELINHA\r\nVALOR UNIDADE: R\$1.020,00",
                'valor' => '9120',
                'valor_promocional' => null,
                'slug' => 'conjunto-de-mesa-bali-telinha',
                'status' => 1,
                'created_at' => '2025-04-01 12:28:57',
                'updated_at' => '2025-04-01 12:28:57',
            ],
            [
                'id' => 86,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebdc686e3a6-collect-01-04-25-.svg',
                'titulo' => 'CONJUNTO DE MESA BALI VAI-VEM',
                'descricao' => "DESCRIÇÃO\r\n\r\nCONJUNTO DE MESA BALI TRAMA VAI E VEM\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NÁUTICA\r\nTECIDO ACQUABLOCK\r\n\r\nMESA BALI TAMPO CUMARU PIZZA DIAMETRO 1,40M\r\nVALOR UNIDADE: R\$6.399,00\r\n\r\nCADEIRA BALI TRAMA VAI E VEM\r\nVALOR UNIDADE: R\$960,00",
                'valor' => '12159',
                'valor_promocional' => null,
                'slug' => 'conjunto-de-mesa-bali-vai-vem',
                'status' => 1,
                'created_at' => '2025-04-01 12:30:32',
                'updated_at' => '2025-04-01 12:30:32',
            ],
            [
                'id' => 87,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebdcbb259e1-collect-01-04-25-.svg',
                'titulo' => 'CONJUNTO DE MESA RAINHA',
                'descricao' => "DESCRIÇÃO\r\n\r\nCONJUNTO DE MESA RAINHA\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NÁUTICA\r\nTECIDO ACQUABLOCK\r\n\r\nMESA BARCELONA TAMPO CUMARU PIZZA DIAMETRO 1,00M\r\nVALOR UNIDADE: R\$3.199,00\r\n\r\nCADEIRA RAINHA\r\nVALOR UNIDADE: R\$2.096,00",
                'valor' => '11583',
                'valor_promocional' => null,
                'slug' => 'conjunto-de-mesa-rainha',
                'status' => 1,
                'created_at' => '2025-04-01 12:31:55',
                'updated_at' => '2025-04-01 12:31:55',
            ],
            [
                'id' => 88,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebdd0d7448e-collect-01-04-25-.svg',
                'titulo' => 'CONJUNTO DE MESA MIAMI',
                'descricao' => "DESCRIÇÃO\r\n\r\nCONJUNTO DE MESA MIAMI\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK\r\n\r\nMESA BARCELONA TAMPO CUMARU GIRATÓRIO RIPADO 1,40M\r\nVALOR UNIDADE: R\$6.329,00\r\n\r\nCADEIRA MIAMI TRAMA TELINHA\r\nVALOR UNIDADE: R\$1.055,00",
                'valor' => '12659',
                'valor_promocional' => null,
                'slug' => 'conjunto-de-mesa-miami',
                'status' => 1,
                'created_at' => '2025-04-01 12:33:17',
                'updated_at' => '2025-04-01 12:33:17',
            ],
            [
                'id' => 89,
                'categoria_id' => 9,
                'promocao_id' => null,
                'imagem' => 'uploads/media_67ebdd72dc37f-collect-01-04-25-.svg',
                'titulo' => 'CONJUNTO DE MESA BALI TRAMA TELINHA',
                'descricao' => "DESCRIÇÃO\r\n\r\nCONJUNTO DE MESA BALI TRAMA TELINHA\r\nESPECIFICAÇÕES:\r\nESTRUTURA EM ALUMINIO\r\nPINTURA ELETROSTATICA\r\nCORDA NAUTICA\r\nTECIDO ACQUABLOCK\r\n\r\nMESA BALI  TAMPO CUMARU PIZZA DIAMETRO 0,90M\r\nVALOR UNIDADE: R\$3.100,00\r\n\r\nCADEIRA BALI TRAMA TELINHA\r\nR\$1.020,00",
                'valor' => '7180',
                'valor_promocional' => null,
                'slug' => 'conjunto-de-mesa-bali-trama-telinha',
                'status' => 1,
                'created_at' => '2025-04-01 12:34:58',
                'updated_at' => '2025-04-01 12:34:58',
            ],
        ]);
    }
}
